models/Post.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $category_id
 * @property integer $status
 * @property integer $create_time
 * @property integer $update_time
 * @property integer $user_id
 *
 * @property Komentar $komentar
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content', 'category_id'], 'required'],
            [['content', 'status'], 'string'],
            [['category_id', 'create_time', 'update_time', 'user_id'], 'integer'],
            [['title'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'category_id' => 'Category ID',
            'status' => 'Status',
            //'create_time' => 'Create Time',
            //'update_time' => 'Update Time',
            'user_id' => 'User ID',
            // 'id' => Yii::t('app', 'ID'),
            // 'title' => Yii::t('app', 'Title'),
            // 'content' => Yii::t('app', 'Content'),
            // 'category_id' => Yii::t('app', 'Category ID'),
            // 'status' => Yii::t('app', 'Status'),
            // 'create_time' => Yii::t('app', 'Create Time'),
            // 'update_time' => Yii::t('app', 'Update Time'),
            // 'user_id' => Yii::t('app', 'User ID'),
        
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKomentar()
    {
        return $this->hasMany(Komentar::className(), ['post_id' => 'id']);
    }



   /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => \yii\behaviors\TimestampBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['create_time', 'update_time'],
                    \yii\db\ActiveRecord::EVENT_BEFORE_UPDATE => 'update_time',
                ],
            ],
            'autouserid' => [
                'class' => \yii\behaviors\BlameableBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['user_id'],
                ],
            ],          
        ];
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\User;
use app\models\PostSearch;
use app\models\PostAdmin;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Status;
use yii\web\ForbiddenHttpException;
use yii\filters\AccessControl;
use kartik\mpdf\Pdf;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    public function behaviors()
    {
        return [
        'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','create','update','delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = 'adminpage';
      

        if( Yii::$app->user->can('admin') ){
            $searchModel = new PostAdmin();

            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

             return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
        }else{

            $searchModel = new PostSearch();

            $param_search = Yii::$app->request->queryParams;
            $param_search['PostSearch']['user_id'] = Yii::$app->session->get('user.id');
            $dataProvider = $searchModel->search($param_search);
            
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

    }




    public function actionPdf() {

        // $searchModel = new StatusSearch();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        
        //  $content = $this->renderPartial('index', [
        //         'searchModel' => $searchModel,
        //         'dataProvider' => $dataProvider,
        //     ]);

        // $id = 1;
        // return $this->renderPartial('view', [
        //     'model' => $this->findModel($id),
        // ]);
        //use kartik\mpdf\Pdf;
        $content = $this->renderPartial('pdf');
           
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_CORE,
        // A4 paper format
        'format' => Pdf::FORMAT_A4,
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT,
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER,
        // your html content input
        'content' => $content,
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting
        'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}',
        // set mPDF properties on the fly
        'options' => ['title' => 'Laporan Tulisan Artikel - E-learning animation SMA MUH 1 Yogyakarta'],
        // call mPDF methods on the fly
        'methods' => [
        'SetHeader'=>['Laporan Tulisan Artikel - E-learning animation SMA MUH 1 Yogyakarta'],
        'SetFooter'=>['{PAGENO}'],
        ]
        ]);

        /*------------------------------------*/
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        $headers = Yii::$app->response->headers;
        $headers->add('Content-Type', 'application/pdf');
        /*------------------------------------*/

        // return the pdf output as per the destination setting
        return $pdf->render();
    }

     public function actionAdmin()
    {
         if( Yii::$app->user->can('admin') )
        {
        $this->layout = 'adminpage';
        $searchModel = new PostAdmin();
        
       $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
         }else{
            throw new ForbiddenHttpException;
            
        }


    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $this->layout = 'adminpage';

        

        return $this->render('view', [
            'model' => $this->findModel($id),
            
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if( Yii::$app->user->can('student') )
        {
            $this->layout = 'adminpage';
            $model = new Post();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                 // return $this->redirect(['view', 'id' => $model->id]);

                 $this->layout = 'adminpage';
                $searchModel = new PostSearch();
                
                $param_search = Yii::$app->request->queryParams;
                $param_search['PostSearch']['user_id'] = Yii::$app->session->get('user.id');

                $dataProvider = $searchModel->search($param_search);

               return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }

        }else{
            throw new ForbiddenHttpException;
            
        }
        
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if(Yii::$app->user->can('student'))
        {

            $this->layout = 'adminpage';
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
               // return $this->redirect(['view', 'id' => $model->id]);

                 $this->layout = 'adminpage';
                $searchModel = new PostSearch();
                
                $param_search = Yii::$app->request->queryParams;
                $param_search['PostSearch']['user_id'] = Yii::$app->session->get('user.id');

                $dataProvider = $searchModel->search($param_search);

               return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]);

            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }else{
            throw new ForbiddenHttpException;
            
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if(Yii::$app->user->can('student'))
        {
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        }else{
            throw new ForbiddenHttpException;
        }
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use mihaildev\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
    <div class="col-md-8">
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        
    </div>
    <div class="col-md-4">
        
    <?= $form->field($model, 'category_id')->dropDownList(
            ArrayHelper::map(app\models\Category::find()->all(),'id','name'),
            ['prompt'=>'Pilih Kategori']
            ) ?>
    </div>
  

   <!--  <?= $form->field($model, 'foto')->textarea(['rows' => 6]) ?>
 -->
</div>

    <?= $form->field($model, 'content')->widget(CKEditor::className(),[
            'editorOptions' => [
                'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                'inline' => false, //по умолчанию false
            ],
            ]); ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>


    <?= $form->field($model, 'globalSearch') ?>

   
    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    
    </div>

    <?php ActiveForm::end(); ?>

</div>
<br>
<br>
<br>

views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\export\ExportMenu;


/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Posts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">

   

<div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Post', ['create'], ['class' => 'btn btn-success']) ?>
         <?php echo Html::a('PRINT', ['/post/pdf'], [
    'class'=>'btn btn-danger', 
    'target'=>'_blank', 
    'data-toggle'=>'tooltip', 
    'title'=>'Will open the generated PDF file in a new window'
]);
?>
    </p>
   
<?php

    $gridColoum = [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'title',
            //'content:ntext',
            //'category_id',
            
            // 'create_time:datetime',
            // 'update_time:datetime',
            // 'user_id',
            [
            
            'attribute' => 'user',
            'value' => 'user.realname',
            
            ],[
            
            'attribute' => 'kategori',
            'value' => 'category.name',
            
            ],
            
            //  [
            //     'class' => 'kartik\grid\EditableColumn',
            //     'header' => 'Status',
            //     'attribute' => 'status',
            // ],
            //'status',
            
            ['class' => 'yii\grid\ActionColumn'],
            ]
    ?>

   <!--  <?= ExportMenu::widget([
            'dataProvider' => $dataProvider,
            'columns' => $gridColoum
        ]);
    ?>
 -->
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions'=>function($model){
                if($model->status == 'publish'){
                    return ['class'=>'success'];
                }elseif ($model->status == 'draf') {
                     return ['class'=>'danger'];
                }
        },
        'columns' => $gridColoum    ]); ?>
   
</div>

views/post/pdf.php
<!DOCTYPE html>
<html>
<body>
   <main>


<?php
    if(Yii::$app->user->can('admin')){

    $posts = app\models\PdfPost::find()
                    //->where(['user_id' => Yii::$app->session->get('user.id')])
                    ->all();
            foreach ($posts as $nama) {
                 $realname = $nama->realname ;
                 $nis = $nama->nis;
                 $telephon = $nama->telepon;
                 $email = $nama->email;

                   $query=app\models\PdfTutorial::findBySql("SELECT * FROM pdf_post");
                $total = $query->count();
            }
    }else{
        $posts = app\models\PdfPost::find()
                    ->where(['user_id' => Yii::$app->session->get('user.id')])
                    ->all();
            foreach ($posts as $nama) {
                 $realname = $nama->realname ;
                 $nis = $nama->nis;
                 $telephon = $nama->telepon;
                 $email = $nama->email;

             $query=app\models\PdfPost::findBySql("SELECT * FROM pdf_post where user_id = ".Yii::$app->session->get('user.id')."");
                $total = $query->count();
               

            }
    }
        ?>

                <div id="main-wrapper">
                    <div class="row">
                        <div class="invoice col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <h3 class="m-b-md"><b><?php if(Yii::$app->user->can('admin')){echo $realname;echo " (super admin)";}else{echo $realname;} ?></b></h3>
                                            <address>
                                                Nis: <?php echo $nis; ?><br>
                                                Phone: <?php echo $telephon; ?><br>
                                                Email: <?php echo $email;?>
                                            </address>
                                        </div>
                                       
                                        <div class="col-md-12">
                                            <hr>
                                            <p>
                                                <strong>Data From</strong><br>
                                                Post<br>
                                                created: <?= date('H:i:s d-m-Y') ?>
                                            </p>
                                        </div>
                                        <div class="col-md-12">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th></th>
                                                        <th>Title</th>
                                                        <th>Status</th>
                                                        <th>Category</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                   <?php 
                                                       foreach ($posts as $post) {
                                                        $no = '-';
                                                        echo '<tr>';
                                                            echo '<td>'. $no .'</td>';
                                                            echo '<td>'. $post->name .'</td>';
                                                            echo '<td>'. $post->status .'</td>';
                                                             echo '<td>'. $post->category .'</td>';
                                                            
                                                            
                                                        echo '</tr>';
                                                        
                                                        }
                                                    ?>
                                                </tbody>
                                            </table>
                                        </div>
                                        <br>
                                        <br>
                                        <div class="col-md-8">
                                            <h3>Thank you !</h3>
                                            <p>Terima kasih telah mengunakan e-learning animasi SMA Muhammadiyah 1 Yogyakarta</p>
                                            
                                        </div>
                                        <div class="col-md-4">
                                            <div class="text-right">
                                                <hr>
                                                <h4 class="no-m m-t-sm">Total Tulisan</h4>
                                                <h2 class="no-m"><?php echo $total;?></h2>
                                                <hr>
                                            </div>
                                        </div>
                                    </div><!--row-->
                                </div>
                            </div>
                        </div>
                    </div><!-- Row -->
                </div><!-- Main Wrapper -->
                
            
        </main><!-- Page Content -->
     
        
    </body>
</html>

views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Update Post: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-view">

   <div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?php echo '<a href="'.\Yii::$app->urlManager->createUrl(['site/post-single', 'id' => $model->id]).'" class="btn btn-danger">Kunjungi Postingan <i class="fa fa-angle-right"></i></a>'; ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'content:ntext',
            //'category_id',
            'status',
            //'create_time:datetime',
            //'update_time:datetime',
            //'user_id',
        ],
    ]) ?>

</div>