models/Tutorial.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tutorial".
 *
 * @property integer $id
 * @property string $judul
 * @property string $file
 * @property string $thumb
 * @property integer $user_id
 * @property string $tag
 * @property integer $subkategori_id
 * @property string $deskripsi
 * @property string $downloads
 * @property string $views
 * @property string $like
 * @property string $share
 * @property string $created
 * @property string $modified
 *
 * @property Subkategori $subkategori
 * @property User $user
 */
class Tutorial extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $file_upload;
   
    
    public static function tableName()
    {
        return 'tutorial';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subkategori_id', 'deskripsi', 'judul'], 'required'],
            [['user_id', 'subkategori_id', 'downloads', 'views', 'like', 'share'], 'integer'],
            [['deskripsi','status'], 'string'],
            [['created', 'modified'], 'safe'],
            [['judul'], 'string', 'max' => 250],
            [['file', 'thumb'], 'string', 'max' => 500],
            [['tag'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'judul' => 'Judul',
            'file' => 'File',
            'thumb' => 'Thumb',
            'user_id' => 'User ID',
            'tag' => 'Tag',
            'subkategori_id' => 'Subkategori ID',
            'deskripsi' => 'deskripsi',
            'downloads' => 'Downloads',
            'views' => 'Views',
            'like' => 'Like',
            'share' => 'Share',
            'status' => 'Status',
            'created' => 'Created',
            'modified' => 'Modified',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubkategori()
    {
        return $this->hasOne(Subkategori::className(), ['id' => 'subkategori_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

controllers/TutorialController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kategori;
use app\models\Tutorial;
use app\models\TutorialSearch;
use app\models\Subkategori;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\data\Pagination;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\web\Response;
use yii\web\Application;
use yii\helpers\Url;
use yii\web\ForbiddenHttpExcaption;
use kartik\mpdf\Pdf;
use yii\data\ArrayDataProvider;
use yii\httpclient\Client;
use yii\helpers\Json;
use linslin\yii2\curl;



/**
 * TutorialController implements the CRUD actions for Tutorial model.
 */
class TutorialController extends Controller
{
    public $modelClass = 'app\models\Tutorial';
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','create','update','delete','getsubkategori'],
                'rules' => [
                    [
                        'actions' => ['index','create','update','delete','getsubkategori'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tutorial models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = 'adminpage';
        
        if( Yii::$app->user->can('admin')){
           $searchModel = new TutorialSearch();
       
           $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);

        }else{

           
            $searchModel = new TutorialSearch();
            $param_search = Yii::$app->request->queryParams;
            $param_search['TutorialSearch']['user_id'] = Yii::$app->session->get('user.id');
            
            $dataProvider = $searchModel->search($param_search);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

     public function actionAdmin()
    {
         if( Yii::$app->user->can('admin') )
        {
        $this->layout = 'adminpage';
        $searchModel = new TutorialSearch();
        
       $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
         }else{
            throw new ForbiddenHttpException;
            
        }


    }

    public function actionPdf() {

        // $searchModel = new StatusSearch();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        
        //  $content = $this->renderPartial('index', [
        //         'searchModel' => $searchModel,
        //         'dataProvider' => $dataProvider,
        //     ]);

        // $id = 1;
        // return $this->renderPartial('view', [
        //     'model' => $this->findModel($id),
        // ]);
        $content = $this->renderPartial('pdf');
           
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_CORE,
        // A4 paper format
        'format' => Pdf::FORMAT_A4,
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT,
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER,
        // your html content input
        'content' => $content,
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting
        'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}',
        // set mPDF properties on the fly
        'options' => ['title' => 'Laporan Tutorial Animasi- E-learning animation SMA MUH 1 Yogyakarta'],
        // call mPDF methods on the fly
        'methods' => [
        'SetHeader'=>['Laporan Tutorial Animasi - E-learning animation SMA MUH 1 Yogyakarta'],
        'SetFooter'=>['{PAGENO}'],
        ]
        ]);

        /*------------------------------------*/
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        $headers = Yii::$app->response->headers;
        $headers->add('Content-Type', 'application/pdf');
        /*------------------------------------*/

        // return the pdf output as per the destination setting
        return $pdf->render();
    }

    
    public function actionGetsubkategorijson($id='')
    {
        if($id == ''){
            $subkategori = Subkategori::find()->asArray()->all();       
        }else{
            $subkategori = Subkategori::find()->where("kategori_id = $id")->asArray()->all();           
        }
         return (json_encode($subkategori));
    }
    
    public function actionIndexkategori($subkategori_id)
    {
        
    }


    /**
     * Displays a single Tutorial model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $subkategori = subkategori::find()
                    ->orderBy('nama ASC')
                    ->all(); 

        $this->layout = 'homepage';
        $model = $this->findModel($id);
        $model->views = $model->views + 1;
        $model->save();
        // $data=Tutorial::find()
                // ->where(['id'=>$id])
                // ->one();
        return $this->render('view', [
            'model' =>  $model,
            'subkategori' => $subkategori,
            // 'data'   =>  $data,
        ]);
    }

    /**
     * Creates a new Tutorial model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'adminpage';
        $model = new Tutorial();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->user_id = Yii::$app->session->get('user.id');
            $model->file_upload = UploadedFile::getInstance($model,'file');
            if($model->file_upload->size > 5000000) {
                \Yii::$app->getSession()->setFlash('error','File yang diupload melebihi 5 MB.');
                return $this->redirect(['create']);    
            }
            else{
                $model->file_upload->saveAs('uploads/tutorial/tutorial_'.$model->id.'.'.$model->file_upload->extension);
            $model->file = 'http://muhi.gamatutor.id/web/uploads/tutorial/tutorial_'.$model->id.'.'.$model->file_upload->extension;
          
              //Init curl
        $curl = new curl\Curl();

        //post http://example.com/
        $response = $curl->setOption(
                CURLOPT_POSTFIELDS, 
                http_build_query(array(
                    'judul' => $model->judul,
                    'file' => $model->file,
                    'subkategori_id' => '3',
                    'deskripsi' => $model->deskripsi,
                    'user_id'=> '223',
                )
            ))
            ->post('http://gamatutor.id/web/index.php?r=service%2Fcreate');


             $model->save();
            return $this->redirect(['view', 'id' => $model->id]); 


        
            }
           


            
            
        } else {
            return $this->render('create', [
                    'model' => $model,
                ]);
        }
    }

    /**
     * Creates counter for like button
    */

    public function actionDownload($id)
    {
        $model = $this->findModel($id);
        $model->downloads = $model->downloads + 1;
        $model->save();
        // $data=Tutorial::find()
                // ->where(['id'=>$id])
                // ->one();
        // return $this->render('like', [
        //     'model' =>  $model,
        //     // 'data'   =>  $data,
        // ]);
        Yii::$app->getResponse()->xSendFile($model->file);
        // return Yii::$app->getResponse()->redirect(Yii::$app->getHomeUrl());
    }

    public function actionLike($id)
    {
        $model = $this->findModel($id);
        $model->like = $model->like + 1;
        $model->save();
        // $data=Tutorial::find()
                // ->where(['id'=>$id])
                // ->one();
        // return $this->render('like', [
        //     'model' =>  $model,
        //     // 'data'   =>  $data,
        // ]);
        return Yii::$app->getResponse()->redirect(Yii::$app->getHomeUrl());
    }

    /**
     * Creates counter for share button
    */

    public function actionShare($id)
    {
        $model = $this->findModel($id);
        $model->share = $model->share + 1;
        $model->save();
        $urlshare=urlencode(Url::to(['tutorial/view','id'=>$model->id],true));
        // $data=Tutorial::find()
                // ->where(['id'=>$id])
                // ->one();
        return Yii::$app->getResponse()->redirect('https://twitter.com/share?url='.$urlshare);
    }

    /**
     * Updates an existing Tutorial model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $this->layout = 'adminpage';
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,

views/tutorial/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Subkategori;
use mihaildev\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\Tutorial */
/* @var $form yii\widgets\ActiveForm */
?>

        <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]); ?>
        
        <div class="row">
            <div class="col-md-8">
                <?= $form->field($model, 'judul')->textInput(['maxlength' => 250]) ?>
                
            </div>
            <div class="col-md-4">
                 <?= $form->field($model, 'subkategori_id')->dropDownList(
            ArrayHelper::map(app\models\Subkategori::find()->all(),'id','nama'),
            ['prompt'=>'Pilih Kategori']
            ) ?>

            </div>
         
        </div>



        <?= $form->field($model, 'file')->fileInput(['accept' => '.zip']) ?>



        <?php 
            if(!empty($model->file)) {
                echo Html::activeHiddenInput($model,'file',['value'=>$model->file]);
                echo '<div class="form-group"><a class="btn btn-success" href="'.$model->file.'">Download File Sekarang</a></div>';
            }
        ?>

        

       

    <?= $form->field($model, 'deskripsi')->widget(CKEditor::className(),[
    'editorOptions' => [
        'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
        'inline' => false, //по умолчанию false
    ],
]); ?>

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

views/tutorial/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TutorialSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tutorial-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'globalSearch') ?>

   

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tutorial/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tutorial */

$this->title = 'Upload Tutorial';
$this->params['breadcrumbs'][] = ['label' => 'Tutorial', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tutorial-create">

    <div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tutorial/index.php
<?php
 
use yii\helpers\Html;
//use yii\grid\GridView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TutorialSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tutorial Anda';
$this->params['breadcrumbs'][] = $this->title;
?>

   

<div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>


<br>
<br>
<br>

    <p>
        <?= Html::a('Upload Tutorial', ['create'], ['class' => 'btn btn-success']) ?>
         <?php echo Html::a('PRINT', ['/tutorial/pdf'], [
    'class'=>'btn btn-danger', 
    'target'=>'_blank', 
    'data-toggle'=>'tooltip', 
    'title'=>'Will open the generated PDF file in a new window'
]);
?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions'=>function($model){
                if($model->status == 'publish'){
                    return ['class'=>'success'];
                }elseif ($model->status == 'draf') {
                     return ['class'=>'danger'];
                }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn','header' => "No"],

            'judul',
            
             [
            
            'attribute' => 'user',
            'value' => 'user.realname',
            
            ],
            'file:ntext',
            [
            
            'attribute' => 'kategori',
            'value' => 'subkategori.nama',
            
            ],
           //'status',
            // 'created',
            // 'modified',

            ['class' => 'yii\grid\ActionColumn','header' => "&nbsp;"],
        ],
    ]); ?>

views/tutorial/pdf.php
<!DOCTYPE html>
<html>
<body>
   <main>


<?php
    if(Yii::$app->user->can('admin')){

    $posts = app\models\PdfTutorial::find()
                    //->where(['user_id' => Yii::$app->session->get('user.id')])
                    ->all();
            foreach ($posts as $nama) {
                 $realname = $nama->realname ;
                 $nis = $nama->nis;
                 $telephon = $nama->telepon;
                 $email = $nama->email;

                  $query=app\models\PdfTutorial::findBySql("SELECT * FROM pdf_tutorial");
                $total = $query->count();
            }
    }else{
        $posts = app\models\PdfTutorial::find()
                    ->where(['user_id' => Yii::$app->session->get('user.id')])
                    ->all();
            foreach ($posts as $nama) {
                 $realname = $nama->realname ;
                 $nis = $nama->nis;
                 $telephon = $nama->telepon;
                 $email = $nama->email;
             $query=app\models\PdfTutorial::findBySql("SELECT * FROM pdf_tutorial where user_id = ".Yii::$app->session->get('user.id')."");
                $total = $query->count();
            }
    }
               
        ?>

                <div id="main-wrapper">
                    <div class="row">
                        <div class="invoice col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <h3 class="m-b-md"><b><?php if(Yii::$app->user->can('admin')){echo $realname;echo " (super admin)";}else{echo $realname;} ?></b></h3>
                                            <address>
                                                Nis: <?php echo $nis; ?><br>
                                                Phone: <?php echo $telephon; ?><br>
                                                Email: <?php echo $email;?>
                                            </address>
                                        </div>
                                       
                                        <div class="col-md-12">
                                            <hr>
                                            <p>
                                                <strong>Data From</strong><br>
                                                Tutorial Animasi<br>
                                                created: <?= date('H:i:s d-m-Y') ?>
                                            </p>
                                        </div>
                                        <div class="col-md-12">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th></th>
                                                        <th>Title</th>
                                                        <th>Status</th>
                                                        <th>Category</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                   <?php 
                                                       foreach ($posts as $post) {
                                                        $no = '-';
                                                        echo '<tr>';
                                                            echo '<td>'. $no .'</td>';
                                                            echo '<td>'. $post->name .'</td>';
                                                            echo '<td>'. $post->status .'</td>';
                                                             echo '<td>'. $post->category .'</td>';
                                                            
                                                            
                                                        echo '</tr>';
                                                        
                                                        }
                                                    ?>
                                                </tbody>
                                            </table>
                                        </div>
                                        <br>
                                        <br>
                                        <div class="col-md-8">
                                            <h3>Thank you !</h3>
                                            <p>Terima kasih telah mengunakan e-learning animasi SMA Muhammadiyah 1 Yogyakarta</p>
                                            
                                        </div>
                                        <div class="col-md-4">
                                            <div class="text-right">
                                                <hr>
                                                <h4 class="no-m m-t-sm">Total Tulisan</h4>
                                                <h2 class="no-m"><?php echo $total;?></h2>
                                                <hr>
                                            </div>
                                        </div>
                                    </div><!--row-->
                                </div>
                            </div>
                        </div>
                    </div><!-- Row -->
                </div><!-- Main Wrapper -->
                
            
        </main><!-- Page Content -->
     
        
    </body>
</html>

views/tutorial/searchresult.php
<?php
/* @var $this yii\web\View */
$this->title = 'Gama Animation Portal';
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\LinkPager;

use yii\data\Pagination;

use yii\helpers\Url;
Html::csrfMetaTags()
?>
    <!--=== Search Block Version 2 ===-->
    <?php
        $form=ActiveForm::begin([
        'method'    =>  'get',
        'action'    =>  Url::toRoute('tutorial/search'),
    ]);
    ?>

<div class="row">
<div class="col-xs-4">

</div>
<div class="col-xs-8">

</div>
</div>              
      
<!-- ======= Banner ======= -->
        <section class="p0 container-fluid banner about_banner">
            <div class="about_banner_opacity">
                 <div class="search-block-v2" ng-app="purchaseOrderApp" ng-controller="purchaseOrderDetailControl">
                    <div class="container">
                        <div class="col-md-8 col-md-offset-2">
                            <br><h2 align="center">Cari Tutorial</h2><br>
                            <div class="input-group">
                                
                                <select name="subkategori_id" class="form-control" style="width: 30%">
                                    <option value="">Sub Kategori</option>
                                    <?php foreach($subkategoris as $subkategori){ 
                                        $selected = "";
                                        if($subkategori->id==$subkategori_id) $selected='selected="selected"';
                                    ?>

                                    <option <?= $selected ?> value="<?php echo $subkategori->id; ?>"><?php echo $subkategori->nama; ?></option>
                                    <?php } ?>
                                </select>
                                <input type="text" name="search" value="<?= $search ?>" style="width: 40%" class="form-control" placeholder="Cari Tutorial Animasi ...">
                                <!-- <input type="hidden" name="_csrf" value="ZEZ6Y0xrY3ARGS42fTwhMQgkDgF6BCEGEx4SMXQMBR4CPy0iPCIwNQ=="> -->
                                <span class="input-group-btn">
                                    <button class="btn-u" type="submit"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                        </div>
                    </div>    
                </div><!--/container-->   
            </div> <!-- End Banner_opacity -->
        </section> <!-- End Banner -->
<!-- ================= /Banner ================ -->

     
    <!-- </form> -->
    <?php
    ActiveForm::end();
    ?>
    <!--=== End Search Block Version 2 ===-->
    <hr />
    <!--=== Search Results ===-->
    <div class="container s-results margin-bottom-50">
        <div class="row">
            <div class="col-md-2 hidden-xs related-search">
                <!-- <div class="row">
                    <div class="col-md-12 col-sm-4">
                        <h3>Pencarian terkait</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Web design company</a></li>     
                            <li><a href="#">Web design tutorials</a></li>   
                            <li><a href="#">Self designing</a></li>   
                        </ul>
                        <hr>
                    </div>    

                    <div class="col-md-12 col-sm-4">    
                        <h3>Tutorial</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Basic Concepts</a></li>     
                            <li><a href="#">‎Building your first web page</a></li>   
                            <li><a href="#">‎Advanced HTML</a></li>   
                        </ul>
                        <hr>
                    </div>    

                    <div class="col-md-12 col-sm-4">
                        <h3>Topik terpopuler</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Bootstrap</a></li>     
                            <li><a href="#">Wrapbootstrap</a></li>     
                            <li><a href="#">Codrops</a></li>     
                        </ul>
                        <hr>
                    </div>    

                    <div class="col-md-12 col-sm-4">                        
                        <h3>Riwayat pencarian</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Web design articles</a></li>   
                            <li><a href="#">Tutorials for web design</a></li>     
                        </ul>
                        <a class="see-all" href="#">See all</a>
                        <hr>
                    </div>    
                </div> -->        
            </div><!--/col-md-2-->

            <div class="col-md-10">
                <span class="results-number"><b>Menemukan sebanyak <?= $count ?> hasil</b></span>
                <!-- Begin Inner Results -->
                <?php
                    foreach($data as $row){
                        ?>
                        <div class="inner-results">
                            <h3><?= Html::a($row->judul, ['tutorial/view', 'id' =>$row->id])?></h3>
                            <p>
                                <?php 
                                    if(strlen($row->deskripsi) > 300){
                                        echo substr($row->deskripsi,0,300).'...';
                                    }else{
                                        echo $row->deskripsi; 
                                    } 
                                ?>
                            </p>   
                        </div>
                        <hr>
                        <?php
                    }
                ?>

                <div class="margin-bottom-30"></div>
                <?= LinkPager::widget(['pagination' => $pagination]) ?>
                

                
            
            </div><!--/col-md-10-->
        </div>        
    </div><!--/container-->     
    <!--=== End Search Results ===-->

<?php
$this->registerCssFile('@web/unify/plugins/line-icons/line-icons.css',['depends'=>'app\assets\AppAsset']);
$this->registerCssFile('@web/unify/plugins/font-awesome/css/font-awesome.min.css',['depends'=>'app\assets\AppAsset']);
$this->registerCssFile('@web/unify/plugins/owl-carousel/owl-carousel/owl.carousel.css',['depends'=>'app\assets\AppAsset']);
$this->registerCssFile('@web/unify/plugins/sky-forms/version-2.0.1/css/custom-sky-forms.css',['depends'=>'app\assets\AppAsset']);
$this->registerCssFile('@web/unify/css/pages/page_search.css',['depends'=>'app\assets\AppAsset']);
?>

views/tutorial/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tutorial */

$this->title = 'Update Tutorial: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tutorial', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tutorial-update">

    <div class="page-title">
                    <h3><?= Html::encode($this->title) ?></h3>
                    <div class="page-breadcrumb">
                        
                    </div>
                </div>
<br>
<br>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>